config/routes.rb
Rails.application.routes.draw do
  resources :projes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/proje.rb
class Proje < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projes_controller.rb
class ProjesController < ApplicationController
  before_action :set_proje, only: [:show, :edit, :update, :destroy]

  # GET /projes
  # GET /projes.json
  def index
    @projes = Proje.all
  end

  # GET /projes/1
  # GET /projes/1.json
  def show
  end

  # GET /projes/new
  def new
    @proje = Proje.new
  end

  # GET /projes/1/edit
  def edit
  end

  # POST /projes
  # POST /projes.json
  def create
    @proje = Proje.new(proje_params)

    respond_to do |format|
      if @proje.save
        format.html { redirect_to @proje, notice: 'Proje was successfully created.' }
        format.json { render :show, status: :created, location: @proje }
      else
        format.html { render :new }
        format.json { render json: @proje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projes/1
  # PATCH/PUT /projes/1.json
  def update
    respond_to do |format|
      if @proje.update(proje_params)
        format.html { redirect_to @proje, notice: 'Proje was successfully updated.' }
        format.json { render :show, status: :ok, location: @proje }
      else
        format.html { render :edit }
        format.json { render json: @proje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projes/1
  # DELETE /projes/1.json
  def destroy
    @proje.destroy
    respond_to do |format|
      format.html { redirect_to projes_url, notice: 'Proje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proje
      @proje = Proje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proje_params
      params.require(:proje).permit(:marka, :urun)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projes_helper.rb
module ProjesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projes/_form.html.erb
<%= form_with(model: proje, local: true) do |form| %>
  <% if proje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proje.errors.count, "error") %> prohibited this proje from being saved:</h2>

      <ul>
      <% proje.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marka %>
    <%= form.text_field :marka %>
  </div>

  <div class="field">
    <%= form.label :urun %>
    <%= form.text_field :urun %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projes/edit.html.erb
<h1>Editing Proje</h1>

<%= render 'form', proje: @proje %>

<%= link_to 'Show', @proje %> |
<%= link_to 'Back', projes_path %>

app/views/projes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projes</h1>

<table>
  <thead>
    <tr>
      <th>Marka</th>
      <th>Urun</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projes.each do |proje| %>
      <tr>
        <td><%= proje.marka %></td>
        <td><%= proje.urun %></td>
        <td><%= link_to 'Show', proje %></td>
        <td><%= link_to 'Edit', edit_proje_path(proje) %></td>
        <td><%= link_to 'Destroy', proje, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proje', new_proje_path %>

app/views/projes/new.html.erb
<h1>New Proje</h1>

<%= render 'form', proje: @proje %>

<%= link_to 'Back', projes_path %>

app/views/projes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marka:</strong>
  <%= @proje.marka %>
</p>

<p>
  <strong>Urun:</strong>
  <%= @proje.urun %>
</p>

<%= link_to 'Edit', edit_proje_path(@proje) %> |
<%= link_to 'Back', projes_path %>